# This is a basic workflow to help you get started with Actions

name: Slack Notifications

on:
  pull_request:
    types: [ labeled ]

jobs:
  notifySlack:
    runs-on: ubuntu-latest
    
    if: ${{ github.event.label.name == 'need-approval' }}
    steps:
      - name: Notify slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: pullRequest,author,eventName # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always()
#         with:
#           args: '{\"channel\":\"C02LV4R4X4Z\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Pull Request:* ${{ github.event.pull_request.title }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Who?:* ${{ github.event.pull_request.user.login }}\n*Need Approval:* ${{ github.event.pull_request.user.login }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"<${{ github.event.pull_request.html_url }}|View Pull Request>\"}}]}'
    

#         uses: pullreminders/slack-action@master
#         env:
#           SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
#           SLACK_CHANNEL: testing
#           SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
#           SLACK_ICON: https://github.com/rtCamp.png?size=48
#           SLACK_MESSAGE: 'Post Content :rocket:'
#           SLACK_TITLE: Post Title
#           SLACK_USERNAME: Shintana
#           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
